FROM archlinux:latest

RUN pacman -Syu --noconfirm
RUN pacman -S --noconfirm archiso

RUN mkdir -p /build /output
WORKDIR /build

COPY packages.x86_64 /build/packages.x86_64

RUN cp -a /usr/share/archiso/configs/releng /build/ \
    && cat /build/packages.x86_64 >> /build/releng/packages.x86_64

WORKDIR /build/releng

RUN mkarchiso -v -w /build/work -o /output .
