name: 'Linux Builder'
description: 'Build custom Linux images with Linux Builder Engine'
author: 'Linux Builder Team'

branding:
  icon: 'box'
  color: 'blue'

inputs:
  api-key:
    description: 'Linux Builder API key'
    required: true
  spec-file:
    description: 'Path to build spec JSON file'
    required: false
    default: 'build-spec.json'
  api-url:
    description: 'Linux Builder API URL'
    required: false
    default: 'https://api.linuxbuilder.io'
  wait:
    description: 'Wait for build to complete'
    required: false
    default: 'true'
  timeout:
    description: 'Build timeout in seconds'
    required: false
    default: '1800'
  compliance:
    description: 'Run compliance check (hipaa, pci-dss, soc2)'
    required: false
    default: ''

outputs:
  build-id:
    description: 'The build ID'
  status:
    description: 'Build status (SUCCESS, FAILED, CANCELLED)'
  docker-image:
    description: 'Docker image reference if available'
  iso-url:
    description: 'ISO download URL if available'
  compliance-score:
    description: 'Compliance score if check was run'

runs:
  using: 'node20'
  main: 'dist/index.js'
